### ISSUE TITLE
WebXR API?

### ISSUE THREAD

**Issue by rogueyoshi** [BabylonJS/BabylonAR#9]
Does BabylonAR leverage the immersive WebXR APIs? We're looking for a framework that uses it while also having image/marker tracking.

**Comment by syntheticmagus** [comment]
@rogueyoshi You shouldn't even need BabylonAR for this; I think Babylon.js will already have everything you've mentioned. Babylon.js supports the latest WebXR draft and a number of extensions, including experimental [image tracking](https://doc.babylonjs.com/typedoc/classes/babylon.webxrimagetracking) capabilities. BabylonAR is an extension repo predominantly used for CV experiments and more custom capabilities that can't be found in browsers; but now that browsers are adding their own image tracking capabilities, I think Babylon.js on it's own will probably have everything you need. For more information, please post questions on the [forum](https://forum.babylonjs.com/c/questions/5). Thanks!
